services:
  - type: web
    name: global-agents-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: >
      bash -lc '
      export API_HOST="${API_HOST:-http://127.0.0.1:${PORT}}";
      # Run worker in background; keep uvicorn as main process
      python -m global_agents.worker.looper &
      exec uvicorn api.main:app --host 0.0.0.0 --port ${PORT}
      '
    healthCheckPath: /api/healthz
    envVars:
      - key: UNIVERSE
        value: EURUSD=X,BTC-USD,ETH-USD,GBPUSD=X,XAUUSD=X
      - key: TF
        value: 1h
      - key: COOLDOWN
        value: 25
      - key: HTTP_TIMEOUT
        value: 60
      - key: REDIS_URL
        value: ""
        sync: false