services:
  - type: web
    name: global-agents-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install --only-binary=:all: numpy==2.2.2 pandas==2.2.3
      pip install -r requirements.txt
    startCommand: >
      bash -lc '
      export API_HOST="http://127.0.0.1:${PORT}";
      uvicorn api.main:app --host 0.0.0.0 --port ${PORT} &
      sleep 12
      python -m global_agents.worker.looper
      '
    healthCheckPath: /api/healthz
    envVars:
      - key: UNIVERSE
        value: EURUSD=X,BTC-USD,ETH-USD,GBPUSD=X,XAUUSD=X
      - key: TF
        value: 1h
      - key: COOLDOWN
        value: 20
      - key: HTTP_TIMEOUT
        value: 20